from __future__ import annotations

from photo_to_gcode.models import ProcessingSettings, Toolpath
from photo_to_gcode.toolpaths import merge_continuous_fill_toolpaths


def _dedupe_consecutive_points(points: list[tuple[float, float]]) -> list[tuple[float, float]]:
    if not points:
        return []

    deduped = [points[0]]
    for point in points[1:]:
        if point != deduped[-1]:
            deduped.append(point)
    return deduped


def generate_gcode(
    toolpaths: list[Toolpath],
    settings: ProcessingSettings,
) -> str:
    toolpaths = merge_continuous_fill_toolpaths(
        toolpaths,
        max_connector_gap_mm=max(1.0, settings.fill_spacing_mm * 3.0),
    )

    lines = [
        "; Generated by Photo to G-code",
        "G21 ; millimeters",
        "G90 ; absolute positioning",
        settings.pen_up_command,
    ]

    if settings.pen_pause_seconds > 0:
        lines.append(f"G4 P{settings.pen_pause_seconds:.2f}")

    for toolpath in toolpaths:
        toolpath_points = _dedupe_consecutive_points(toolpath.points)
        if len(toolpath_points) < 2:
            continue

        start_x, start_y = toolpath_points[0]
        lines.append(f"G0 X{start_x:.3f} Y{start_y:.3f}")
        lines.append(settings.pen_down_command)

        if settings.pen_pause_seconds > 0:
            lines.append(f"G4 P{settings.pen_pause_seconds:.2f}")

        draw_points = toolpath_points[1:]
        first_x, first_y = draw_points[0]
        lines.append(f"G1 X{first_x:.3f} Y{first_y:.3f} F{settings.feed_rate}")
        for x_pos, y_pos in draw_points[1:]:
            lines.append(f"G1 X{x_pos:.3f} Y{y_pos:.3f}")

        lines.append(settings.pen_up_command)
        if settings.pen_pause_seconds > 0:
            lines.append(f"G4 P{settings.pen_pause_seconds:.2f}")

    lines.append(settings.pen_up_command)
    return "\n".join(lines) + "\n"
